# all: zad1

# zad1: zad1.c
# 	gcc -Wall -fsanitize=address,undefined -o zad1 zad1.c

# .PHONY: clean
# clean:
# 	rm -f zad1

CC=gcc
CFLAGS=-Wall -fsanitize=address,undefined
LDFLAGS=-fsanitize=address,undefined